language: node_js
node_js:
  - "node"
  - "12"

cache: yarn

script:
  - yarn run check

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

after_success:
  - yarn global add codecov && codecov
